-- ============================================================
-- Seed: known sources (properties pre-filled from feed analysis)
-- and country code normalisation map
-- ============================================================

insert into sources (id, network, has_coordinates, has_departure_date, has_transport_type)
values
  ('daisycon-prijsvrij',        'daisycon',     false, true,  false),
  ('daisycon-dutchflyguys',     'daisycon',     false, true,  true),
  ('tradetracker-bungalownet',  'tradetracker', true,  false, false),
  ('daisycon-solmar',           'daisycon',     false, true,  true)
on conflict (id) do nothing;

-- ------------------------------------------------------------------ country_code_map
-- Covers all raw values observed or likely in Dutch travel feeds.
-- Extend as new values appear in the unresolved_country_log.
insert into country_code_map (raw_value, iso2) values
  -- Dutch full names
  ('Spanje',              'ES'),
  ('Spanje ',             'ES'),
  ('Italie',              'IT'),
  ('Italië',              'IT'),
  ('Griekenland',         'GR'),
  ('Turkije',             'TR'),
  ('Portugal',            'PT'),
  ('Nederland',           'NL'),
  ('Belgie',              'BE'),
  ('België',              'BE'),
  ('Frankrijk',           'FR'),
  ('Duitsland',           'DE'),
  ('Oostenrijk',          'AT'),
  ('Zwitserland',         'CH'),
  ('Kroatie',             'HR'),
  ('Kroatië',             'HR'),
  ('Bulgarije',           'BG'),
  ('Cyprus',              'CY'),
  ('Malta',               'MT'),
  ('Egypte',              'EG'),
  ('Marokko',             'MA'),
  ('Tunesie',             'TN'),
  ('Tunesië',             'TN'),
  ('Verenigde Staten',    'US'),
  ('Mexico',              'MX'),
  ('Cuba',                'CU'),
  ('Curacao',             'CW'),
  ('Curaçao',             'CW'),
  ('Aruba',               'AW'),
  ('Dominican Republic',  'DO'),
  ('Dominicaanse Republiek', 'DO'),
  ('Thailand',            'TH'),
  ('Bali',                'ID'),  -- Bali used as country name in some feeds
  ('Indonesie',           'ID'),
  ('Indonesië',           'ID'),
  ('Kaapverdische Eilanden', 'CV'),
  ('Kaapverdie',          'CV'),
  ('Jordanie',            'JO'),
  ('Jordanië',            'JO'),
  ('Israel',              'IL'),
  ('Israël',              'IL'),
  ('Namibie',             'NA'),
  ('Tanzania',            'TZ'),
  ('Kenya',               'KE'),
  ('Kenia',               'KE'),
  ('Slowakije',           'SK'),
  ('Tsjechie',            'CZ'),
  ('Tsjechië',            'CZ'),
  ('Hongarije',           'HU'),
  ('Polen',               'PL'),
  ('Noorwegen',           'NO'),
  ('Zweden',              'SE'),
  ('Finland',             'FI'),
  ('Denemarken',          'DK'),
  ('IJsland',             'IS'),
  ('Ierland',             'IE'),
  ('Schotland',           'GB'),
  ('Engeland',            'GB'),
  ('Groot-Brittannie',    'GB'),
  ('Groot-Brittannië',    'GB'),
  ('Verenigd Koninkrijk', 'GB'),
  ('Albanie',             'AL'),
  ('Albanië',             'AL'),
  ('Montenegro',          'ME'),
  ('Slovenie',            'SI'),
  ('Slovenië',            'SI'),
  ('Servie',              'RS'),
  ('Servië',              'RS'),
  ('Bosnie',              'BA'),
  ('Bosnië',              'BA'),
  ('Macedonie',           'MK'),
  ('Macedonië',           'MK'),
  -- ISO-2 codes (already correct, passthrough)
  ('ES', 'ES'), ('IT', 'IT'), ('GR', 'GR'), ('TR', 'TR'),
  ('PT', 'PT'), ('NL', 'NL'), ('BE', 'BE'), ('FR', 'FR'),
  ('DE', 'DE'), ('AT', 'AT'), ('CH', 'CH'), ('HR', 'HR'),
  ('BG', 'BG'), ('CY', 'CY'), ('MT', 'MT'), ('EG', 'EG'),
  ('MA', 'MA'), ('TN', 'TN'), ('US', 'US'), ('MX', 'MX'),
  ('CU', 'CU'), ('CW', 'CW'), ('AW', 'AW'), ('DO', 'DO'),
  ('TH', 'TH'), ('ID', 'ID'), ('CV', 'CV'), ('JO', 'JO'),
  ('IL', 'IL'), ('NA', 'NA'), ('TZ', 'TZ'), ('KE', 'KE'),
  ('SK', 'SK'), ('CZ', 'CZ'), ('HU', 'HU'), ('PL', 'PL'),
  ('NO', 'NO'), ('SE', 'SE'), ('FI', 'FI'), ('DK', 'DK'),
  ('IS', 'IS'), ('IE', 'IE'), ('GB', 'GB'), ('AL', 'AL'),
  ('ME', 'ME'), ('SI', 'SI'), ('RS', 'RS'), ('BA', 'BA'),
  ('MK', 'MK'), ('LU', 'LU'), ('LT', 'LT'), ('LV', 'LV'),
  ('EE', 'EE'), ('RO', 'RO'), ('UA', 'UA'), ('RU', 'RU'),
  -- English names (sometimes appear in international feeds)
  ('Spain',        'ES'), ('Italy',    'IT'), ('Greece',    'GR'),
  ('Turkey',       'TR'), ('Portugal', 'PT'), ('France',    'FR'),
  ('Germany',      'DE'), ('Austria',  'AT'), ('Croatia',   'HR'),
  ('Bulgaria',     'BG'), ('Cyprus',   'CY'), ('Malta',     'MT'),
  ('Egypt',        'EG'), ('Morocco',  'MA'), ('Tunisia',   'TN'),
  ('Netherlands',  'NL'), ('Belgium',  'BE'), ('Switzerland','CH'),
  ('Hungary',      'HU'), ('Poland',   'PL'), ('Norway',    'NO'),
  ('Sweden',       'SE'), ('Denmark',  'DK'), ('Iceland',   'IS'),
  ('Ireland',      'IE'), ('Slovenia', 'SI'), ('Serbia',    'RS'),
  ('Albania',      'AL'), ('Montenegro','ME')
on conflict (raw_value) do nothing;
